### PR TITLE
Support Laravel 9

### LINKED ISSUE #11: Laravel 9 Support
Hi,

Is there any plan to support Laravel 9?

### PR DESCRIPTION
**Pull request by nessimabadi**
Adds support to Laravel 9
Fix #11

### CODE REVIEW

**Comment by wmandai** [comment]
@asantibanez Any chance we can get this merged?

**Comment by heloufir** [comment]
@asantibanez any idea when this PR can be merged? We can't install the package with Laravel v9.

**Comment by arianmasselink** [comment]
@asantibanez Any chance this can get merged?

**Comment by laraben** [comment]
Can this be merged please ?

**Comment by asantibanez** [comment]
Added support for L9 and L10. 👍

**Pull request closed without merging**
